version: "3.7"
services:
    apache:
        container_name: apache-php-fpm
        build: "./images/apache"
        environment:
            DOCUMENTROOT: $DOCUMENTROOT
            PHPSERVER: $PHPSERVER
        volumes:
            - ${HOST_PROJECT_DIR}:${DOCUMENTROOT}:ro
        ports:
            - '${HOST_PORT}:80'
        networks:
            phpfpmnetwork:
                aliases:
                    - apache
    phpserver:
        container_name: php-fpm-symfony
        # image: php-fpm-symfony
        build:
            context: "./images/php"
            args:
                - TIMEZONE
        volumes:
            - ${HOST_PROJECT_DIR}:${DOCUMENTROOT}:rw
        environment:
            XDEBUG_CONFIG: $XDEBUG_CONFIG
        networks:
            phpfpmnetwork:
                aliases:
                    - ${PHPSERVER}
networks:
    phpfpmnetwork:
