version: "3.7"
services:
    apache:
        image: httpd:2.4-alpine
        deploy:
            replicas: 1
        configs:
            - source: httpd-conf
              target: /usr/local/apache2/conf/httpd.conf
        environment:
            DOCUMENTROOT: $DOCUMENTROOT
            PHPSERVER: $PHPSERVER
        volumes:
            - type: bind
              source: ${HOST_PROJECT_DIR}
              target: ${DOCUMENTROOT}
              read_only: true
        ports:
            - '${HOST_PORT}:80'
        networks:
            phpfpmnetwork:
                aliases:
                    - apache
    phpserver:
        image: besogon1/php-fpm-dbs:1.0
        deploy:
            replicas: 1
        configs:
            - source: php-ini
              target: /usr/local/etc/php/php.ini
            - source: php-fpm
              target: /usr/local/etc/php-fpm.conf
        ports:
            - '${XDEBUG_PORT}:80'
        volumes:
            - type: bind
              source: ${HOST_PROJECT_DIR}
              target: ${DOCUMENTROOT}
        environment:
            XDEBUG_CONFIG: $XDEBUG_CONFIG
        networks:
            phpfpmnetwork:
                aliases:
                    - ${PHPSERVER}
networks:
    phpfpmnetwork:

configs:
    httpd-conf:
        file: ./images/apache/conf/httpd.conf
    php-ini:
        file: ./images/php/conf/php.ini
    php-fpm:
        file: ./images/php/conf/php-fpm.conf
